### ISSUE TITLE
Convert HEX without '#'

### ISSUE THREAD

**Issue by felipecustodio** [kevscript/vscolors#1]
Hey @kevscript, how are you?
Great extension, it's the only color format converter 
that really worked perfectly for me.

I'm having a bit of trouble with HEX colors. 
When you double click a text to select the color to convert, 
VS Code does not include the hashtag character.

Example:

Double click the string:

"#C9533E",

Right click, convert to RGB:

![image](https://user-images.githubusercontent.com/4261743/107072746-2f04e400-67c5-11eb-8a93-30b354f12676.png)

Do you think it would be possible to:
remove the '#' character from the regex,
when converting back, replace the selection + 1 character to the left?

Since 'rgb' and 'hsl' both have the name strings before, 
it's very distinguishable from HEX colors, it could work.

If you think it's a good idea or there's a better solution, let me know and I can PR it. =)

**Comment by kevscript** [comment]
Sorry for very late answer, I didn't think my extension was being used!

I get what you mean, and it applies to all the other formats to. You can't really select any of them with a double-click.

From my pov, if we want to change the logic on how you parse hex values, we probably should do the same for **all** the formats purely for consistency purposes. But it should still be able to handle basic/full formats.

The `#value`, `rgb(value)`, `hsl(value)`, etc. offer reliable bounderies to recognize and parse the values.

So it would mean **expanding** use cases, which would introduce a level of complexity I'm not sure I can handle. 
At first glance, parsing stripped formats like `000`, `0,0,0`, `0, 0%, 0%`, `0,0,0,0%` to the right ones (on top of the rest) seems like quite a hassle. 
It would need an overhaul of the logic, especialy if we need to depend on, parse and modify text outside of our selection on top of that.
